import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Yihone Chu
 *
 */
public final class RSSAggregrator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregrator() {
    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree feedElement = new XMLTree1(url);
        if (feedElement.label().equals("rss")
                && feedElement.hasAttribute("version")
                && feedElement.attributeValue("version").equals("2.0")) {

            XMLTree feedChild = feedElement.child(0);

            outputHeader(feedChild, out); //Outputs Header
            //Outputs each item
            for (int i = 0; i < feedChild.numberOfChildren(); i++) {
                if (feedChild.child(i).label().equals("item")) {
                    processItem(feedChild.child(i), out);
                }
            }
            outputFooter(out); //Outputs the footer
        } else {
            out.println("Not valid RSS");
        }
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        /*
         * If child element of title exists, title becomes label of the child of
         * title tag.If child element of title tag does not exists, title is
         * Empty Title
         */
        String title = "Empty Title";
        if (channel.child(getChildElement(channel, "title"))
                .numberOfChildren() > 0) {
            title = channel.child(getChildElement(channel, "title")).child(0)
                    .label();
        }
        /*
         * If child element of description exists, description becomes label of
         * the child of description tag.If child element of description tag does
         * not exists, description is No description
         */

        String description = "No description";
        if (channel.child(getChildElement(channel, "description"))
                .numberOfChildren() > 0) {
            description = channel.child(getChildElement(channel, "description"))
                    .child(0).label();
        }
        /*
         * Link Tag must exist and its child element must exist as well link
         * becomes the label of the child element of link tag.
         */
        String link = channel.child(getChildElement(channel, "link")).child(0)
                .label();

        //Outputs to the file
        out.println("<html>");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println(" <h1><a href=\"" + link + "\">" + title + "</a></h1>");
        out.println(" <p>" + description + "</p>");
        out.println(" <table border=\"1\">");
        out.println(" <tr>");
        out.println("  <th>Date</th>");
        out.println("  <th>Source</th>");
        out.println("  <th>News</th>");
        out.println(" </tr>");

    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        //prints out end tags.
        out.println(" </table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int index = -1;
        int i = 0;
        while (index == -1 && i < xml.numberOfChildren()) {
            if (xml.child(i).isTag() && xml.child(i).label().equals(tag)) {
                index = i;
            }
            i++;
        }
        return index;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //Variables and their initial values.
        String title = "No title available";
        String link = "Link does not exist";
        String pubDate = "No date available";
        String source = "No source available";

        int indexOfTitle = getChildElement(item, "title");
        int indexOfDescription = getChildElement(item, "description");
        int indexOfLink = getChildElement(item, "link");
        int indexOfPubDate = getChildElement(item, "pubDate");
        /*
         * If link tag exists, link becomes label of link tag's child
         */
        if (indexOfLink != -1) {
            link = item.child(indexOfLink).child(0).label();
        }
        /*
         * If pubDate tag exists, pubDate becomes the label of the child element
         * of link tag.
         */
        if (indexOfPubDate != -1) {
            pubDate = item.child(indexOfPubDate).child(0).label();
        }

        /*
         * If source tag exists, and child element of source tag exists source
         * becomes the label of the child element of tag.
         *
         */
        int indexOfSource = getChildElement(item, "source");
        if (indexOfSource != -1
                && item.child(indexOfSource).numberOfChildren() > 0) {
            source = item.child(indexOfSource).child(0).label();
        } else if (indexOfSource != -1
                && item.child(indexOfSource).numberOfChildren() == 0) {
            source = item.child(indexOfSource).attributeValue("url");
        }

        out.println(" <tr>");
        out.println("  <td>" + pubDate + "</td>");

        /*
         * If child text node of source tag exists prints hyperlink with child
         * label if text node of source tag does not exist prints hyperlink with
         * "No source available"
         */

        if (indexOfSource != -1) {
            out.println("  <td><a href=\""
                    + item.child(indexOfSource).attributeValue("url") + "\">"
                    + source + "</a></td>");
        } else {
            out.println("  <td>" + source + "</td>");
        }

        if (indexOfTitle != -1
                && item.child(indexOfTitle).numberOfChildren() > 0) {
            /*
             * If title tag exists and child exists. Title becomes the child
             * element of title tag.
             */
            title = item.child(indexOfTitle).child(0).label();
        } else if (indexOfTitle != -1
                && item.child(indexOfTitle).numberOfChildren() == 0
                && indexOfDescription != -1
                && item.child(indexOfDescription).numberOfChildren() > 0) {
            /*
             * If title tag exists but has no children and description tag
             * exists and has children title becomes text child of description
             * tag
             */
            title = item.child(indexOfDescription).child(0).label();
        } else if (indexOfTitle == -1 && indexOfDescription != -1
                && item.child(indexOfDescription).numberOfChildren() > 0) {
            /*
             * If title tag does not exist and description exists and has text
             * child title becomes text child of description.
             */
            title = item.child(indexOfDescription).child(0).label();
        }

        /*
         * If link exists, print title with link. Else print title.
         */
        if (indexOfLink != -1) {
            out.println(
                    "  <td><a href =\"" + link + "\">" + title + "</a></td>");
        } else {
            out.println("  <td>" + title + "</td>");
        }
        out.println(" </tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */

    public static void main(String[] args) {

        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.println("Name of XML file with list of RSS URL? ");
        String fileName = in.nextLine();
        XMLTree xml = new XMLTree1(fileName);

        out.println("Name of HTML that will be created? ");
        String outName = in.nextLine();
        SimpleWriter htmlOut = new SimpleWriter1L(outName);

        htmlOut.println("<html>");
        htmlOut.println(" <head>");
        htmlOut.println("  <title>Top Stories</title>");
        htmlOut.println(" </head>");
        htmlOut.println(" <body>");
        htmlOut.println("  <h2>Top Stories</h2>");
        htmlOut.println("  <ul>");

        for (int i = 0; i < xml.numberOfChildren(); i++) {
            String url = xml.child(i).attributeValue("url");
            String file = xml.child(i).attributeValue("file");
            String name = xml.child(i).attributeValue("name");
            SimpleWriter outFeed = new SimpleWriter1L(file);
            processFeed(url, file, outFeed);
            htmlOut.println(
                    "   <li><a href=\"" + file + "\">" + name + "</a></li>");
            outFeed.close();
        }
        htmlOut.println("  </ul>");
        htmlOut.println(" </body >");
        htmlOut.println("</html>");

        in.close();
        out.close();
        htmlOut.close();
    }

}
